name: 🔎 SubFinder - DNS Enumeration

on:
    workflow_dispatch:

jobs:
  subfinder-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: SubFinder - DNS Enumeration
        uses: projectdiscovery/subfinder-action@main
        with:
          list: list.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: subfinder.log
          path: subfinder.log
